server:
  port: 8092

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 数据库配置；启动时配置数据库资源信息
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    pool-name: Retail_HikariCP
    minimum-idle: 15 #最小空闲连接数量
    idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
    maximum-pool-size: 25 #连接池最大连接数，默认是10
    auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
    max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
    connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
    connection-test-query: SELECT 1
  type: com.zaxxer.hikari.HikariDataSource

# Mybatis 配置
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名映射开关
    map-underscore-to-camel-case: true

# 微信公众号对接
weixin:
  config:
    originalid: gh_b10e448c9117
    token: b8b6
    app-id: wxdce92b6187c545ed
    app-secret: d33783cadf36b0cfa3854f26b4b74448
    template_id: -JfVkAq_upTA-eSPA5kU6sLq-8s_3r8oibULNMEoLo8

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000150644409
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCEIKBjNp5piOtIJrWg2XuGGBq2WwTYwwajqWJrbM/NAY7NVoKP4JyRD8ehiwBLzSfp0UP8f/efWhHDfrGSZAqhrzMq8s9+E0EtKKI1yWPWZmlEoH9FIF47lpxj0WwieQfXj6RgJSF7qmtgXJj4NNlS4sgYFy/fK2QnDEGcX1byGQZkjl3vIJPXD04es6KDy5mOhrlI5h/ok9cnq9607FiIEuWMJkXkhMKY2M1lQuo1KOrboOZ6ByjHLym2S9niYg3dDLA11za2jC72MoUEk/7VnvAiQERPY+UrRm85/LHJKzxEpVS08bEGhvS6iULI+wReuwr336BEDUgwB9N4uvJ/AgMBAAECggEADJF18DoP04Ycq15TRJurblP4poP98AiNJyBDpmhRU/Tj+pBSFxGMkxfnK2yneI5pT4qCZxBdI6FTsz7n8T7m6/5YZat3JUz7lCobU/Z2MrzHIqoJsS+lBxIKikwvdxAAOPcG8cZWawcI87+bJXERgxrjYbdC7H2aJ0S5MQC4qoqnuhotDpIQbNqnZJKgs5cQDxa3llbeCiRwBH71lQ32TtFYOM5Z0ag4tG/V8aJzN7ms5h5dKMBC+Jf7F0j3+RKW7tPyoOaIMuRkjku2hIEIsC8RgSKTbwKaFkM1wGgronBb2asfvY3SmgglbayCc+Oj9bqMiiiqgjhO85P4355MsQKBgQDJFUeI92SItnCFTBU34h0s0Rw0jfdYEyTeiBodi5ybjO93hgHfb6NtFPtiSgxfcvziWI3CMMss/VBDqtOlZ4Kq/r8vYDQ0SziwHFS51+EVGg4hOgSERb/ZAlUvk8ulnq/5dax6W8zgE1Zl6sZfi7wTs1EYCbKW9aGsd2ycLXT0uwKBgQCoNlAlq8zW2tjsK6WsfbfNUaEbelwUlYQ8gbdI7A+e46nVlYShlwtztkVMKjoJ44/1y3Y4cb+RUAhOIkyf0pCKeqSAY5ehXWv+NPATRqui9/D+3OVoa/MDAgqgVQzTjZzsKPJjj14jAQn6kufCSePdJgNwenys35fUES/aa+m/DQKBgHNWkFSgynqcYsgijt0iBmgJfasrbx+Gw5Qc7xXZWbfjTAv7wqE9sLjF2zdSj+xD0YenEZC8Wh3xIpPdrU5npAye2Fy9StRf/SEO7w42JHXtHwOx+ptAQr2f1+rVVG8oKXnmJEt+0nIIxXrqAmUVioimRzKJhXWPaO+7BIJElJw3AoGATqKdUw7+Qk6qa7V3zKw0uXH4m6zW0PSYjeSh9yALqV6KbYNpLlU7EEvcF2ACI89S5DfKO1bJlDfSuhwEsA4ybdopfq+QGepfasX6mThHUncQHUTMpcUZJIXWy98WkOs5uZjmvy4tdrWsoYv9dfEu6Zo0r2dDU1lvU775HOWnrx0CgYEAqoGEv4ETlDelVJNeA1eeDj6XrsHIw4fkKskNPDW/lgmfAoo+yQ4XqVtK9dIYkfpQfx+BVY2+N8cn6O8vmu8lqxjux6i/jc1oYo8aPAsVISwZrthOHVhvI3e18xtCt15p5KokQXI8SZyGQwl2+Ks9s05P1udAbMVUH6BkuHK4AHo=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtby/x24bWSpfD5nuCbnwD76dVbNq/Ws5MLvzDwzfqOIJu2vjGF5Rqb5CG2994Y9lSo4bNPCPyksllaWOZzb2R62KF6bVWHu+2BMLQh4RIaf5/vpuRHCeGjzcgfO6t9KmjAAJDEEh5HVLeH+f5j8B/aG621vFgEei0tahtQjSe1odZUbAlC4/paB9OIpOjbXEQNLAIq1DzhCRiZEM8Ssgyf0FUCVQKK00xLfbmhq+bxEfkbLCZXX98t/WO56dKIl++VVLmNkcxG2fTrYas7iB2I3vyvTxNUdh4AGz7Vg2/boZjYbqxyjdef2ypumRy5Z49yBHvofS61iAGlPYcWf97QIDAQAB
  notify_url: http://fcr-studio.natapp1.cc/api/v1/alipay/alipay_notify_url
  return_url: https://www.apple.com/shop/buy-iphone/iphone-16-pro
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml