# 命令执行 docker-compose -f docker-compose-environment.yml up -d
version: '3.9'

services:
  # mysql
  mysql-spay:
    image: mysql:8.0.32
    container_name: mysql-spay
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "23306:3306"
    volumes:
      # 挂载本地初始化脚本
      - ./mysql/sql:/docker-entrypoint-initdb.d
      # 修改：使用独立的命名卷
      - mysql-spay-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s
    networks:
      - spay-network

  # phpmyadmin https://hub.docker.com/_/phpmyadmin
  phpmyadmin-spay:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin-spay
    ports:
      - 8898:80
    environment:
      - PMA_HOST=mysql-spay
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD= ${MYSQL_ROOT_PASSWORD}
    depends_on:
      mysql-spay:
        condition: service_healthy
    networks:
      - spay-network

  # Redis
  redis-spay:
    image: redis:6.2
    container_name: redis-spay
    restart: always
    ports:
      - 26379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    networks:
      - spay-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  # RedisAdmin https://github.com/joeferner/redis-commander
  redis-admin-spay:
    image: spryker/redis-commander:0.8.0
    container_name: redis-admin
    hostname: redis-commander
    restart: always
    ports:
      - 8082:8081
    environment:
      - REDIS_HOSTS=local:redis-spay:6379:${REDIS_PASSWORD}
      - HTTP_USER=${ADMIN_USER}
      - HTTP_PASSWORD=${ADMIN_PASSWORD}
      - LANG=C.UTF-8
      - LANGUAGE=C.UTF-8
      - LC_ALL=C.UTF-8
    networks:
      - spay-network
    depends_on:
      redis-spay:
        condition: service_healthy

# 声明顶级网络和数据卷
networks:
  spay-network:
    driver: bridge

volumes:
    mysql-spay-data: